#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../common.sh"
cd "$CODES_DIR"

FAIRNESS_SET="${FAIRNESS_SET:-ERDINC_PSR,ERDINC_ESR,ERDINC_PESR,ERDINC_PC,ERDINC_EC,ERDINC_PEC,CPEA,CSA,CLEXMMFPEA,CLEXMMFSA}"
IN_FILE="${IN_FILE:-inst/inst2020/Drahi_1.csv}"
NB_STAGE="${NB_STAGE:-3}"
CHILDS="${CHILDS:-2}"
PERIODS="${PERIODS:-8}"
J="${J:-5}"
THETA="${THETA:-0.2}"
AVG_D="${AVG_D:-100.0}"
DEV_D="${DEV_D:-10.0}"
DEMAND_PROFILE="${DEMAND_PROFILE:-mixed}"
BATTERY_SCALE="${BATTERY_SCALE:-1.0}"
PV_SCALE="${PV_SCALE:-1.0}"
CONDITIONAL_STAGE="${CONDITIONAL_STAGE:-2}"
FAIRNESS_MMR="${FAIRNESS_MMR:-1.2}"
FAIRNESS_ABS_TOL="${FAIRNESS_ABS_TOL:-0.0}"
LEX_EPS_ABS="${LEX_EPS_ABS:-1.0}"
OUT_CSV="${OUT_CSV:-$RESULTS_MODELS_DIR/conditional_fairness_report.csv}"
OUT_CSV_HOUSE="${OUT_CSV_HOUSE:-$RESULTS_MODELS_DIR/conditional_fairness_report_by_house.csv}"
OUT_CSV_DIAGNOSTICS="${OUT_CSV_DIAGNOSTICS:-$RESULTS_MODELS_DIR/conditional_fairness_diagnostics.csv}"

export FAIRNESS_SET IN_FILE NB_STAGE CHILDS PERIODS J THETA AVG_D DEV_D
export DEMAND_PROFILE BATTERY_SCALE PV_SCALE CONDITIONAL_STAGE FAIRNESS_MMR
export FAIRNESS_ABS_TOL LEX_EPS_ABS OUT_CSV OUT_CSV_HOUSE OUT_CSV_DIAGNOSTICS

julia --quiet --startup-file=no --history-file=no run_conditional_fairness.jl
