#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../common.sh"
INST_FOLDER="${INST_FOLDER:-$DEFAULT_INST_FOLDER}"
INSTANCE_FROM="${INSTANCE_FROM:-1}"
INSTANCE_TO="${INSTANCE_TO:-10}"
NBSTAGE="${NBSTAGE:-6}"
CHILDS="${CHILDS:-6}"
PERIODS="${PERIODS:-4}"
J_SET="${J_SET:-5,10}"
THETA_SET="${THETA_SET:-0.2,0.6}"
AVG_D_SET="${AVG_D_SET:-100.0}"
DEV_D_SET="${DEV_D_SET:-10.0,20.0}"
DEMAND_PROFILE_SET="${DEMAND_PROFILE_SET:-mixed}"
BATTERY_SCALE_SET="${BATTERY_SCALE_SET:-1.0}"
PV_SCALE_SET="${PV_SCALE_SET:-1.0}"
OUT_CSV="${OUT_CSV:-$RESULTS_MODELS_DIR/vss_none_S6_C6_P4.csv}"
export INST_FOLDER INSTANCE_FROM INSTANCE_TO NBSTAGE CHILDS PERIODS
export J_SET THETA_SET AVG_D_SET DEV_D_SET DEMAND_PROFILE_SET
export BATTERY_SCALE_SET PV_SCALE_SET OUT_CSV
exec julia --quiet "$CODES_DIR/run_vss_none_experiments.jl"
