#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../common.sh"
cd "$CODES_DIR"

FAIRNESS_COMPARISON_DIR="${FAIRNESS_COMPARISON_DIR:-$RESULTS_MODELS_DIR/fairness_comparison}"
MANIFEST_PATH="${MANIFEST_PATH:-$FAIRNESS_COMPARISON_DIR/config_manifest.csv}"
CONDITIONAL_STAGE_SET="${CONDITIONAL_STAGE_SET:-2,3,4,5,6}"
INSTANCES_PER_TREE="${INSTANCES_PER_TREE:-5}"
VALIDATION_MODE="${VALIDATION_MODE:-main}"
VALIDATE_STAGE1_EQUIVALENCE="${VALIDATE_STAGE1_EQUIVALENCE:-true}"
REFERENCE_HASHES_PATH="${REFERENCE_HASHES_PATH:-$RESULTS_MODELS_DIR/fairness_comparison/source_hashes_before.txt}"
VALIDATION_LOG="${VALIDATION_LOG:-$FAIRNESS_COMPARISON_DIR/validation.log}"

export FAIRNESS_COMPARISON_DIR MANIFEST_PATH CONDITIONAL_STAGE_SET INSTANCES_PER_TREE
export VALIDATION_MODE VALIDATE_STAGE1_EQUIVALENCE REFERENCE_HASHES_PATH

julia --quiet --startup-file=no --history-file=no validate_fairness_comparison.jl 2>&1 | tee "$VALIDATION_LOG"
