#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../common.sh"
FAIRNESS_SET="LEXMMFPEA"
TREE_SET="${TREE_SET:-6:4:4}"
INST_FOLDER="${INST_FOLDER:-$DEFAULT_INST_FOLDER}"
INSTANCE_FROM="${INSTANCE_FROM:-1}"
INSTANCE_TO="${INSTANCE_TO:-10}"
J_SET="${J_SET:-5,10}"
THETA_SET="${THETA_SET:-0.2,0.6}"
AVG_D_SET="${AVG_D_SET:-100.0}"
DEV_D_SET="${DEV_D_SET:-10.0,20.0}"
DEMAND_PROFILE_SET="${DEMAND_PROFILE_SET:-mixed}"
BATTERY_SCALE_SET="${BATTERY_SCALE_SET:-2.0}"
PV_SCALE_SET="${PV_SCALE_SET:-1.0}"
OUT_CSV="${OUT_CSV:-$RESULTS_SENSITIVITY_DIR/fairness_sensitivity_battery_LEXMMFPEA_report.csv}"
OUT_CSV_HOUSE="${OUT_CSV_HOUSE:-$RESULTS_SENSITIVITY_DIR/fairness_sensitivity_battery_LEXMMFPEA_report_by_house.csv}"
SCRIPT_NAME="script_SENSITIVITY_BATTERY_LEXMMFPEA_S6_C4_P4.sh"
export SCRIPT_NAME INST_FOLDER FAIRNESS_SET TREE_SET INSTANCE_FROM INSTANCE_TO
export J_SET THETA_SET AVG_D_SET DEV_D_SET DEMAND_PROFILE_SET BATTERY_SCALE_SET PV_SCALE_SET
export OUT_CSV OUT_CSV_HOUSE
exec "$SCRIPT_DIR/../models/script.sh" "$@"
